# Generated by Django 4.1.5 on 2023-01-14 23:46

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Academico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado", models.DateField(auto_now_add=True, verbose_name="Criado")),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Modificado"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("curso", models.CharField(max_length=100, verbose_name="Curso")),
                (
                    "instituicao",
                    models.CharField(max_length=100, verbose_name="Instituição"),
                ),
                ("dataInicio", models.DateField(verbose_name="Data início")),
                ("dataConclusao", models.DateField(verbose_name="Data Conclusão")),
                (
                    "descricaoP1",
                    models.TextField(max_length=2000, verbose_name="Descrição 1/3"),
                ),
                (
                    "descricaoP2",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Descricao 2/3"
                    ),
                ),
                (
                    "descricaoP3",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Descrição 3/3"
                    ),
                ),
                (
                    "textButtom",
                    models.CharField(max_length=50, verbose_name="Texto Botão"),
                ),
            ],
            options={
                "verbose_name": "Acadêmico",
                "verbose_name_plural": "Acadêmico",
            },
        ),
        migrations.CreateModel(
            name="BoasVindas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado", models.DateField(auto_now_add=True, verbose_name="Criado")),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Modificado"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("titulo", models.CharField(max_length=100, verbose_name="Titulo")),
                (
                    "mensagem",
                    models.TextField(max_length=2000, verbose_name="Mensagem"),
                ),
                ("link", models.URLField(verbose_name="Link")),
                (
                    "textButtom",
                    models.CharField(max_length=50, verbose_name="Texto do Botão"),
                ),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to=core.models.get_file_path,
                        variations={"thumb": (450, 225)},
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=1000, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "BoaVinda",
                "verbose_name_plural": "BoasVindas",
            },
        ),
        migrations.CreateModel(
            name="Certificados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado", models.DateField(auto_now_add=True, verbose_name="Criado")),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Modificado"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("titulo", models.CharField(max_length=100, verbose_name="Título")),
                (
                    "instituicao",
                    models.CharField(max_length=100, verbose_name="Instituição"),
                ),
                ("urlValidacao", models.URLField(verbose_name="URL Validação")),
                ("dataConclusao", models.DateField(verbose_name="Data Conclusão")),
                ("cargaHoraria", models.IntegerField(verbose_name="Carga Horária")),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to=core.models.get_file_path,
                        variations={"thumb": (450, 225)},
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=1000, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
            },
        ),
        migrations.CreateModel(
            name="Conhecimentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado", models.DateField(auto_now_add=True, verbose_name="Criado")),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Modificado"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("titulo", models.CharField(max_length=100, verbose_name="Título")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "nivel",
                    models.IntegerField(verbose_name="Nivel de Conhecimento 0-10"),
                ),
                (
                    "icone",
                    models.CharField(max_length=200, verbose_name="Font Awesome"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Projetos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado", models.DateField(auto_now_add=True, verbose_name="Criado")),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Modificado"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("titulo", models.CharField(max_length=100, verbose_name="Título")),
                ("comentario", models.TextField(verbose_name="Comentário")),
                ("urlgit", models.URLField(verbose_name="URL GitHub")),
                ("urlsite", models.URLField(verbose_name="URL Site")),
                ("dataConclusao", models.DateField(verbose_name="Data Conclusão")),
                ("cargaHoraria", models.IntegerField(verbose_name="Carga Horária")),
                ("peso", models.IntegerField(verbose_name="Peso do Projeto")),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to=core.models.get_file_path,
                        variations={"thumb": (450, 225)},
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=1000, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
            },
        ),
    ]
